---
- hosts: localhost
  become: yes
  tasks:
    - name: Apt Update
      apt:
        upgrade: dist
        update_cache: yes
    
    - name: Install Libvirt
      apt:
        name: "{{ package }}"
      vars:
        package:
        - libvirt-bin
        - libvirt-dev
        - qemu-utils
        - qemu
  
    - name: Restart Libvirt
      command: /etc/init.d/libvirt-bin restart
    
    - name: Create libvirt group
      group:
        name: libvirtd
        state: present
    
    - name: Make libvirt root
      user: 
        name: livirtd
        append: yes
        group: root
    
    - name: Install Vagrant
      apt:
        deb: https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
    
    - name: Create mount point for NVMe drive
      file:
        path: /mnt/nvme
        state: directory
        mode: 0755

    - name: Create NVMe Partion
      parted:
        device: /dev/nvme01n1
        label: gpt
        state: present
    
    - name: Create ext4 filesystem on NVMe drive
      filesystem:  
        dev: /dev/nvme0n1p1
        fstype: ext4

    - name: Mount NVMe drive
      mount:
        path: /mnt/nvme
        src: UUID=f9e96a4e-f913-4e0a-86d4-df9ba2639d85
        fstype: ext4
        opts: defaults
        state: present
    
    - name: Create libvirt and vagrant box folders
      file:
        path: /mnt/nvme/{{ directory }}
        state: directory
        mode: 0755
        vars:
          directory:
          - .libvirt
          - .vagrant_boxes

    - name: Move libvirt storage to nvme
      command: "{{ cmd }}"
      vars:
        cmd:
          - virsh pool-destroy default
          - virsh pool-undefine default
          - virsh pool-define-as --name default --type dir --target /mnt/nvme/.libvirt
          - virsh pool-autostart default
          - virsh pool-start default
    
    - name: Install Vagrant Plugin and Set Env Variable
      command: "{{ cmd }}"
      vars:
        cmd:
          - export VAGRANT_HOME=/mnt/nvme/.vagrant_boxes
          - vagrant plugin install vagrant-libvirt
    
    - name: Set Vagrant env variable for box file location
      lineinfile: 
        path: /root/.bash_profile
        line: export VAGRANT_HOME=/mnt/nvme/.vagrant_boxes/
        
